//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task1.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все символы должны быть буквы..
        /// </summary>
        internal static string AllLettersMessage {
            get {
                return ResourceManager.GetString("AllLettersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть такое слово..
        /// </summary>
        internal static string AlreadyExistsMessage {
            get {
                return ResourceManager.GetString("AlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите слово длиной от 8 до 30 символов:.
        /// </summary>
        internal static string EnterWordPrompt {
            get {
                return ResourceManager.GetString("EnterWordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержит неверное количество повторяющихся символов или новые символы..
        /// </summary>
        internal static string InvalidCharacterCountMessage {
            get {
                return ResourceManager.GetString("InvalidCharacterCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка: длина слова должна быть от 8 до 30 символов и все символы - буквы..
        /// </summary>
        internal static string LengthError {
            get {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок {0}, введите слово:.
        /// </summary>
        internal static string PlayerEnter {
            get {
                return ResourceManager.GetString("PlayerEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок {0} ввел слово: {1}.
        /// </summary>
        internal static string PlayerEntered {
            get {
                return ResourceManager.GetString("PlayerEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок {0} проиграл! Невозможно использовать слово: {1}\nПричина: {2}.
        /// </summary>
        internal static string PlayerLoose {
            get {
                return ResourceManager.GetString("PlayerLoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно! Первичное слово: .
        /// </summary>
        internal static string PrimaryWordSuccess {
            get {
                return ResourceManager.GetString("PrimaryWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышено время ожидания ввода слова..
        /// </summary>
        internal static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте снова:.
        /// </summary>
        internal static string TryAgainPrompt {
            get {
                return ResourceManager.GetString("TryAgainPrompt", resourceCulture);
            }
        }
    }
}
